doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver:   pdo_mysql
        charset: utf8mb4
        server_version: '8.0'
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          datetime_immutable: App\Infrastructure\Share\Persistence\Doctrine\Types\DateTimeType
          email: App\Infrastructure\Share\Persistence\Doctrine\Types\EmailType
          hashed_password: App\Infrastructure\Share\Persistence\Doctrine\Types\HashedPasswordType
        mapping_types:
          uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/persistence/mapping/domain'
                prefix: 'App\Domain'
                alias: Domain
            Projections:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/persistence/mapping/projections'
                prefix: 'App\Infrastructure'
                alias: Projections
